safe: true
markdown: kramdown
pygments: true
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Sergey Kazakov
    # url:  http://example.com/
    company:
        name: Yandex
        url:  http://ya.ru

fork_url: https://github.com/shower/shower
progress: true
line_numbers: true
